import Badge from './Badge';

/** Marks AI output that came from the backend's mock LLM rather than a real model. */
export default function MockBadge({ source }) {
  if (source !== 'mock') return null;
  return (
    <Badge variant="warning" title="Generated by the backend's mock LLM (MOCK_LLM is enabled), not by a real model.">
      Mock AI
    </Badge>
  );
}
